### ISSUE TITLE
Introduction grammar problem

### ISSUE THREAD

**Issue by kayiwa** [bigmachine-io/imposter-roadmap#1]
## What's the problem? 

The sentence below just reads wrong. 

This is what I read:
```md
I know more than a Kim's: the doers
```

This is what I think it should be:
```md
I know more than a few Kim's: the doers
```

## How are you reading the book?

I am reading this on macOS both ePub/PDF (Publisher's version 0.0.2)

**Comment by robconery** [comment]
Cheers thanks! Fixed.
