### ISSUE TITLE
Considered & is/wonder/haven't/know - tense disagreement

### ISSUE THREAD

**Issue by peterlanoie** [bigmachine-io/imposter-roadmap#10]
## Where'd you find this? Page number from PDF would be helpful

46

## What's the problem? 

This is what I read:
```md
If you ever considered a powerful person in your company who is a complete ass 
and wonder why they haven’t been fired, it’s because of whom they know.
```
(following paragraphs is similar.)

This is what I think it should be:
Not 100% confident on this... but I think there's a disagreement of tenses with "considered" and the rest.
```md
is => was
wondered
hadn't
knew
```
or
```
consider
```

**Comment by robconery** [comment]
Just a jammed up sentence altogether... I removed.
