### ISSUE TITLE
The 48 Laws of Power

### ISSUE THREAD

**Issue by peterlanoie** [bigmachine-io/imposter-roadmap#11]
## Where'd you find this? Page number from PDF would be helpful

53

## What's the problem? 

This is what I read:
```md
The 48 Laws of Power, which I mentioned above
```

A search for "48 Laws" starting here going backwards gets us to page 577. I encountered the section on page 43 where you mention "The Laws of Power" and it seemed to be missing something.
```
I love and hate this book at the same time.
```
I was confused here as I didn't recall the mention of a book at this point. Maybe something was deleted unintentionally?

**Comment by robconery** [comment]
Fixed this and rewrote the entire chapter...
