### ISSUE TITLE
Wrong word

### ISSUE THREAD

**Issue by RazorAnt** [bigmachine-io/imposter-roadmap#2]
## Where'd you find this? Page number from PDF would be helpful

Just show me what to do. 4th paragraph 

## What's the problem? 

This is what I read:
```md
I will be mentioning Obsidian throughout this book, but just now you can replace it with your favorite note-taking app.
```

This is what I think it should be:
```md
I will be mentioning Obsidian throughout this book, but just **know** you can replace it with your favorite note-taking app.
```

## How are you reading the book?

Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)

Epub 0.9.0

**Comment by robconery** [comment]
You're awesome thanks Al!
