### ISSUE TITLE
my favorite (sorry, “favourite”) is ColorLouvers

### ISSUE THREAD

**Issue by peterlanoie** [bigmachine-io/imposter-roadmap#24]
## Where'd you find this? Page number from PDF would be helpful
168
## What's the problem? 

This is what I read:
```md
my favorite (sorry, “favourite”) is ColorLouvers
```

This is what I think it should be:
```md
my favorite (sorry, “favourite”) is ColourLovers
```
Kinda funny that their own site isn't consistent with the spelling of "color".

**Comment by robconery** [comment]
Ha ha - not sure if I was trying to be funny here or not... but thanks :).
