### ISSUE TITLE
Word Usage

### ISSUE THREAD

**Issue by astocks** [bigmachine-io/imposter-roadmap#3]
## What's the problem? 
Possible incorrect word. 

This is what I read:
```md
That said, it’s entirely possibly you’re going to find an issue with some content in this book.

```

This is what I think it should be:
```md

That said, it’s entirely possible you’re going to find an issue with some content in this book.

```

## How are you reading the book?

EPUB via Reader Readwise app on iOS mobile

**Comment by robconery** [comment]
Thank you! Fixed...
