### ISSUE TITLE
Unclear wording

### ISSUE THREAD

**Issue by astocks** [bigmachine-io/imposter-roadmap#4]
## What's the problem? 

This is what I read:
```md
I know more than a Kims: the doers.
```

This is what I think it should be:
```md
I know more than a few Kims: the doers.
```

## How are you reading the book?
EPUB iOS 
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)

**Comment by robconery** [comment]
Thanks Adam! Fixed...
