### ISSUE TITLE
Word choice?

### ISSUE THREAD

**Issue by astocks** [bigmachine-io/imposter-roadmap#5]
## What's the problem? 
Feels like it should be ‘skips’ or ‘leaves out’
This is what I read:
```md
This gives you a nice calendar view of things you’ve worked on, but unfortunately skips leaves out notes and the importance of note-taking, which is a bummer.
```

This is what I think it should be:
```md
This gives you a nice calendar view of things you’ve worked on, but unfortunately leaves out notes and the importance of note-taking, which is a bummer.
```

## How are you reading the book?
EPUB iOS 
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)

**Comment by robconery** [comment]
Yep - thanks!
