### ISSUE TITLE
Odd sentence 

### ISSUE THREAD

**Issue by RazorAnt** [bigmachine-io/imposter-roadmap#6]
## Where'd you find this? Page number from PDF would be helpful

Finding Your Tribe, Building Your Network

## What's the problem? 

This is what I read:
```md
but if you’re interested and want to read a book that will blow your mind, Sapiens by Yuval Noah Harari will is a book you should read.
```

This is what I think it should be:
```md
but if you’re interested and want to read a book that will blow your mind, Sapiens by Yuval Noah Harari is a book you should read.
```

Remove "will"?

## How are you reading the book?

Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)

Epub 0.9.0

**Comment by robconery** [comment]
Thanks!
