### ISSUE TITLE
Wrong where

### ISSUE THREAD

**Issue by RazorAnt** [bigmachine-io/imposter-roadmap#7]
## Where'd you find this? Page number from PDF would be helpful

Developing Your Empathetic Shell

## What's the problem? 

This is what I read:
```md
“they tend to where their emotions on their sleeve”
```

This is what I think it should be:
```md
“they tend to **wear** their emotions on their sleeve”
```

## How are you reading the book?

Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)

Epub 0.9.0

**Comment by robconery** [comment]
Cheers thanks Al!
